version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysqle
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    # volumes:
    #   - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    #   - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-api
    ports: 
      - "3000:3000"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

# volumes:
#   db_data: